### ISSUE TITLE
Add optional Wave-Ice Coupling to NUOPC cap

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/CICE#52]
Implementation of Wave-Ice Coupling between WW3 and CICE6 requires added exchange fields between WW3 and CICE6 in the NUOPC cap. These field exchanges need to be optionally allowed only when WW3-CICE6 coupling is desired.

**Comment by junwang-noaa** [comment]
@DeniseWorthen So this update allows two way wave/sea-ice coupling, is there documentation available on improving ww3/sea-ice forecast with this update?

**Comment by DeniseWorthen** [comment]
I know there are papers that Lettie and CC did regarding the impact of wave-ice coupling (in CESM) but I don't know the literature well. I think it would be a very interesting feature to test---and see the impact it has on sea-ice predictions.
